### ISSUE TITLE
"Change layer view" button is confusing

### ISSUE THREAD

**Issue by reprapperMC** [alephobjects/Cura#109] opened 2015-05-29 13:30 UTC
When Layers is selected in the view menu a small layers graphic is appearing at the bottom of the layer scroll bar at the bottom. This is built from LulzBot-devel branch, commit c84496d9e791bc89599992f80a0fa11f3fac61f3

![screenshot - 05292015 - 07 29 00 am](https://cloud.githubusercontent.com/assets/849151/7883525/65d8ecfa-05d4-11e5-8a46-96bbfbe726ef.png)

**Comment by kakaroto** [comment] 2015-05-29 14:45
That's not a bug. It's a feature introduced in 15.0. When you click on that
button it will toggle the single layer view. Basically click on it, and the
scroll bar allows you to view a specific layer only vs.  all layers below
it.

**Comment by reprapperMC** [comment] 2015-05-29 15:41
Ok, makes sense. We've already talked about this, but for documentation, we need to replace the graphic as it is confusing and too small.

**Comment by reprapperMC** [comment] 2015-05-29 16:58
See commit 3350ad7352f597b3f6c7c4e17738d5808daed0d6 for the addition of the layer toggle graphic. We'll have to see how this looks as it is very small. It may be best to make the button larger than what it is currently sized down to in Cura.

**Comment by kakaroto** [comment] 2015-05-29 17:41
New graphics was added and resized, it's not less confusion. Closing the issue.

**Closed by kakaroto** 2015-05-29 17:41 UTC
